## Amazon Sales Report

##### Importing the required Libraries

In [60]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

##### Introduction to the dataset

In [91]:
# Loading the dataset
df = pd.read_csv("Amazon_Sale_Report.csv")
print("Dataset loaded successfully!")

Dataset loaded successfully!

In [92]:
# Shape of the dataset
df.shape

(128976, 21)

In [93]:
# Display the first 5 rows of the dataset
df.head()

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Category,Size,Courier Status,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,B2B,fulfilled-by,New,PendingS
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,T-shirt,S,On the Way,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,False,Easy Ship,NaN,NaN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,Shirt,3XL,Shipped,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,False,Easy Ship,NaN,NaN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,Shirt,XL,Shipped,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,True,NaN,NaN,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,Blazzer,L,On the Way,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,False,Easy Ship,NaN,NaN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,Trousers,3XL,Shipped,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,False,NaN,NaN,NaN

In [ ]:
# Display the information about the dataset, including column names, data types, and non-null counts
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128976 entries, 0 to 128975
Data columns (total 21 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   index               128976 non-null  int64
 1   Order ID            128976 non-null  object
 2   Date                128976 non-null  object
 3   Status              128976 non-null  object
 4   Fulfilment          128976 non-null  object
 5   Sales Channel       128976 non-null  object
 6   ship-service-level  128976 non-null  object
 7   Category            128976 non-null  object
 8   Size                128976 non-null  object
 9   Courier Status      128976 non-null  object
 10  Qty                 128976 non-null  int64
 11  currency            121176 non-null  object
 12  Amount              121176 non-null  float64
 13  ship-city           128941 non-null  object
 14  ship-state          128941 non-null  object
 15  ship-postal-code    128941 non-null  float64
 16  ship-country        128941 non-null  object
 17  B2B                 128976 non-null  bool
 18  fulfilled-by        39263 non-null   object
 19  New                 0 non-null       float64
 20  PendingS            0 non-null       float64
dtypes: bool(1), float64(4), int64(2), object(14)
memory usage: 19.8+ MB

In [ ]:
# Display the summary statistics of the dataset, including count, mean, standard deviation, minimum, maximum, and quartiles for numerical columns
df.describe()

,index,Qty,Amount,ship-postal-code,New,PendingS
count,128976.000000,128976.000000,121176.000000,128941.000000,0.0,0.0
mean,64486.130427,0.904401,648.562176,463945.677744,NaN,NaN
std,37232.897832,0.313368,281.185041,191458.488954,NaN,NaN
min,0.000000,0.000000,0.000000,110001.000000,NaN,NaN
25%,32242.750000,1.000000,449.000000,382421.000000,NaN,NaN
50%,64486.500000,1.000000,605.000000,500033.000000,NaN,NaN
75%,96730.250000,1.000000,788.000000,600024.000000,NaN,NaN
max,128974.000000,15.000000,5584.000000,989898.000000,NaN,NaN

In [ ]:
# Display the data types of each column in the dataset
df.dtypes

order_id               object
Date                   object
status                 object
fulfilment             object
sales_channel          object
ship_service_level     object
category               object
size                   object
courier_status         object
qty                     int64
currency               object
amount                float64
ship_city              object
ship_state             object
ship_postal_code      float64
ship_country           object
b2b                      bool
dtype: object

In [ ]:
# Display the number of missing values in each column of the dataset
df.isnull().sum()

index                      0
Order ID                   0
Date                       0
Status                     0
Fulfilment                 0
Sales Channel              0
ship-service-level         0
Category                   0
Size                       0
Courier Status             0
Qty                        0
currency                7800
Amount                  7800
ship-city                 35
ship-state                35
ship-postal-code          35
ship-country              35
B2B                        0
fulfilled-by           89713
New                   128976
PendingS              128976
dtype: int64

In [119]:
df.duplicated().sum()

np.int64(0)

In [118]:
print("Duplicate Rows:", df.duplicated().sum())
print("Duplicate Order IDs:", df['order_id'].duplicated().sum())

Duplicate Rows: 0
Duplicate Order IDs: 8574

In [120]:
df[df['order_id'] == df['order_id'].value_counts().idxmax()]

,index,order_id,status,fulfilment,sales_channel,ship_service_level,category,size,courier_status,qty,currency,amount,ship_city,ship_state,ship_postal_code,ship_country,b2b
74586,74585,171-5057375-2831560,Cancelled,Merchant,Amazon.in,Standard,Perfume,Free,On the Way,0,INR,797.14,CHENNAI,TAMIL NADU,600044.0,IN,False
74587,74586,171-5057375-2831560,Cancelled,Merchant,Amazon.in,Standard,Shirt,3XL,On the Way,0,INR,463.81,CHENNAI,TAMIL NADU,600044.0,IN,False
74588,74587,171-5057375-2831560,Cancelled,Merchant,Amazon.in,Standard,Shirt,XXL,On the Way,0,INR,385.71,CHENNAI,TAMIL NADU,600044.0,IN,False
74589,74588,171-5057375-2831560,Cancelled,Merchant,Amazon.in,Standard,Shirt,3XL,On the Way,0,INR,380.00,CHENNAI,TAMIL NADU,600044.0,IN,False
74590,74589,171-5057375-2831560,Cancelled,Merchant,Amazon.in,Standard,Shirt,3XL,On the Way,0,INR,332.38,CHENNAI,TAMIL NADU,600044.0,IN,False
74591,74590,171-5057375-2831560,Cancelled,Merchant,Amazon.in,Standard,T-shirt,3XL,On the Way,0,INR,651.43,CHENNAI,TAMIL NADU,600044.0,IN,False
74592,74591,171-5057375-2831560,Cancelled,Merchant,Amazon.in,Standard,T-shirt,3XL,On the Way,0,INR,652.38,CHENNAI,TAMIL NADU,600044.0,IN,False
74593,74592,171-5057375-2831560,Cancelled,Merchant,Amazon.in,Standard,Trousers,XXL,On the Way,0,INR,380.00,CHENNAI,TAMIL NADU,600044.0,IN,False
74594,74593,171-5057375-2831560,Cancelled,Merchant,Amazon.in,Standard,Shirt,3XL,On the Way,0,INR,414.29,CHENNAI,TAMIL NADU,600044.0,IN,False
74595,74594,171-5057375-2831560,Cancelled,Merchant,Amazon.in,Standard,Blazzer,3XL,On the Way,0,INR,665.71,CHENNAI,TAMIL NADU,600044.0,IN,False
74596,74595,171-5057375-2831560,Cancelled,Merchant,Amazon.in,Standard,Shirt,XXL,On the Way,0,INR,286.67,CHENNAI,TAMIL NADU,600044.0,IN,False
74597,74596,171-5057375-2831560,Cancelled,Merchant,Amazon.in,Standard,Blazzer,3XL,On the Way,0,INR,818.10,CHENNAI,TAMIL NADU,600044.0,IN,False

##### Handling Duplicate datas

In [114]:
df[df.duplicated()]

,index,order_id,status,fulfilment,sales_channel,ship_service_level,category,size,courier_status,qty,currency,amount,ship_city,ship_state,ship_postal_code,ship_country,b2b
201,6,408-5748499-6859555,Shipped,Amazon,Amazon.in,Expedited,T-shirt,L,Shipped,1,INR,653.0,CHANDIGARH,CHANDIGARH,160036.0,IN,False
202,7,406-7807733-3785945,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,Shirt,S,Shipped,1,INR,399.0,HYDERABAD,TELANGANA,500032.0,IN,False
203,8,407-5443024-5233168,Cancelled,Amazon,Amazon.in,Expedited,T-shirt,3XL,Cancelled,0,INR,NaN,HYDERABAD,TELANGANA,500008.0,IN,False
204,9,402-4393761-0311520,Shipped,Amazon,Amazon.in,Expedited,Shirt,XXL,Shipped,1,INR,363.0,Chennai,TAMIL NADU,600041.0,IN,False
205,10,407-5633625-6970741,Shipped,Amazon,Amazon.in,Expedited,Shirt,S,Shipped,1,INR,685.0,CHENNAI,TAMIL NADU,600073.0,IN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6640,6278,171-5170733-7855514,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,T-shirt,XS,Shipped,1,INR,582.0,HYDERABAD,TELANGANA,500083.0,IN,False
6641,6279,403-8137343-5206760,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,T-shirt,XS,Shipped,1,INR,801.0,KALPETTA,KERALA,673122.0,IN,False
6642,6280,408-1575454-3263526,Shipped - Returned to Seller,Merchant,Amazon.in,Standard,Blazzer,M,Shipped,1,INR,690.0,CHENNAI,TAMIL NADU,600049.0,IN,False
6643,6281,171-2918708-7197155,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,Blazzer,XXL,Shipped,1,INR,658.0,PUNE,MAHARASHTRA,412207.0,IN,False
6644,6282,406-7244956-4740355,Shipped,Amazon,Amazon.in,Expedited,Trousers,XL,Shipped,1,INR,540.0,RAJKOT,Gujarat,360001.0,IN,False

In [115]:
df = df.drop_duplicates()

In [116]:
print(df.duplicated().sum())

0

##### Handling Missing datas

In [97]:
df.drop(columns=['New', 'PendingS'], inplace=True)

In [121]:
df.drop(columns='index', inplace=True)

In [98]:
df.dropna(subset=[
    'ship-city',
    'ship-state',
    'ship-postal-code',
    'ship-country'
], inplace=True)

In [99]:
df.loc[
    (df['currency'].isna()) & (df['ship-country'] == 'IN'),
    'currency'
] = 'INR'

In [100]:
df.isnull().sum()

index                     0
Order ID                  0
Date                      0
Status                    0
Fulfilment                0
Sales Channel             0
ship-service-level        0
Category                  0
Size                      0
Courier Status            0
Qty                       0
currency                  0
Amount                 7798
ship-city                 0
ship-state                0
ship-postal-code          0
ship-country              0
B2B                       0
fulfilled-by          89691
dtype: int64

In [101]:
df[df['Amount'].isnull()]['Courier Status'].value_counts()

Courier Status
Cancelled     5938
On the Way    1736
Unshipped      124
Name: count, dtype: int64

In [102]:
df[df['Courier Status'] == 'Unshipped']['Sales Channel'].value_counts()

Sales Channel
Amazon.in     6554
Non-Amazon     124
Name: count, dtype: int64

In [103]:
print(df['Courier Status'].value_counts())

print("\nSales Channel for Unshipped orders:")
print(df[df['Courier Status'] == 'Unshipped']['Sales Channel'].value_counts())

Courier Status
Shipped       109458
On the Way      6867
Unshipped       6678
Cancelled       5938
Name: count, dtype: int64

Sales Channel for Unshipped orders:
Sales Channel
Amazon.in     6554
Non-Amazon     124
Name: count, dtype: int64

In [104]:
pd.crosstab(
    df['Fulfilment'],
    df['fulfilled-by'],
    dropna=False
)

fulfilled-by  Easy Ship    NaN
Fulfilment
Amazon                0  89691
Merchant          39250      0

In [105]:
df.drop(columns=['fulfilled-by'], inplace=True)

In [106]:
print(df['Status'].unique())
print(df['Courier Status'].unique())

['Cancelled' 'Shipped - Delivered to Buyer' 'Shipped'
 'Shipped - Returned to Seller' 'Shipped - Rejected by Buyer'
 'Shipped - Lost in Transit' 'Shipped - Out for Delivery'
 'Shipped - Returning to Seller' 'Shipped - Picked Up' 'Pending'
 'Pending - Waiting for Pick Up' 'Shipped - Damaged' 'Shipping']
['On the Way' 'Shipped' 'Cancelled' 'Unshipped']

In [107]:
df.columns

Index(['index', 'Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel',
       'ship-service-level', 'Category', 'Size', 'Courier Status', 'Qty',
       'currency', 'Amount', 'ship-city', 'ship-state', 'ship-postal-code',
       'ship-country', 'B2B'],
      dtype='object')

In [108]:
df.drop(columns=['Date'], inplace=True)

In [109]:
# Convert column names to snake_case for consistency and easier access

df.rename(columns={
    'Order ID': 'order_id',
    'Status': 'status',
    'Fulfilment': 'fulfilment',
    'Sales Channel': 'sales_channel',
    'ship-service-level': 'ship_service_level',
    'Category': 'category',
    'Size': 'size',
    'Courier Status': 'courier_status',
    'Qty': 'qty',
    'currency': 'currency',
    'Amount': 'amount',
    'ship-city': 'ship_city',
    'ship-state': 'ship_state',
    'ship-postal-code': 'ship_postal_code',
    'ship-country': 'ship_country',
    'B2B': 'b2b',
    'Year': 'year',
    'Month': 'month',
    'Month_Number': 'month_number',
    'Day': 'day',
    'Weekday': 'weekday'
}, inplace=True)

In [110]:
# Display the first 20 rows of orders with a quantity of 0, showing relevant columns for analysis (To Confirm that qty is 0 means status is Cancelled)

df[df['qty'] == 0][[
    'order_id',
    'status',
    'courier_status',
    'amount',
    'qty',
    'category'
]].head(20)

                order_id     status courier_status   amount  qty  category
0    405-8078784-5731545  Cancelled     On the Way   647.62    0   T-shirt
3    403-9615377-8133951  Cancelled     On the Way   753.33    0   Blazzer
8    407-5443024-5233168  Cancelled      Cancelled      NaN    0   T-shirt
23   404-6019946-2909948  Cancelled     On the Way   570.48    0   T-shirt
29   404-5933402-8801952  Cancelled     On the Way      NaN    0     Shirt
65   171-4137548-0481151  Cancelled      Cancelled      NaN    0     Shirt
83   404-6522553-9345930  Cancelled     On the Way  1105.36    0   T-shirt
84   403-9950518-0349133  Cancelled      Cancelled      NaN    0     Shirt
95   405-9112089-3379536  Cancelled      Cancelled      NaN    0     Shirt
101  402-7841951-1872363  Cancelled      Cancelled      NaN    0   T-shirt
132  171-0293372-4913973  Cancelled      Cancelled      NaN    0   T-shirt
139  403-6442534-2769112  Cancelled      Cancelled      NaN    0  Trousers
155  402-8078642-8565124  Cancelled      Cancelled      NaN    0     Shirt
165  406-0218328-1773963  Cancelled      Cancelled      NaN    0     Shirt
178  171-1224053-5752314  Cancelled     On the Way   463.81    0  Trousers
203  407-5443024-5233168  Cancelled      Cancelled      NaN    0   T-shirt
216  403-5456917-5571511  Cancelled      Cancelled      NaN    0   Blazzer
227  407-4936046-5852304  Cancelled     On the Way  1249.11    0   T-shirt
228  407-4936046-5852304  Cancelled     On the Way  1058.93    0   T-shirt
243  404-0634392-1837110  Cancelled      Cancelled      NaN    0  Trousers

In [111]:
categorical_cols = df.select_dtypes(include=['object', 'bool']).columns.tolist()
print(categorical_cols)

['order_id', 'status', 'fulfilment', 'sales_channel', 'ship_service_level', 'category', 'size', 'courier_status', 'currency', 'ship_city', 'ship_state', 'ship_country', 'b2b']

In [112]:
df.dtypes

index                   int64
order_id               object
status                 object
fulfilment             object
sales_channel          object
ship_service_level     object
category               object
size                   object
courier_status         object
qty                     int64
currency               object
amount                float64
ship_city              object
ship_state             object
ship_postal_code      float64
ship_country           object
b2b                      bool
dtype: object

##### Exploratory Data Analysis (EDA) and Visualization

In [122]:
# Categorical columns and Numerical columns
categorical_cols = df.select_dtypes(include=['object', 'bool']).columns.tolist()
print(categorical_cols)
print()
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
print(numerical_cols)

['order_id', 'status', 'fulfilment', 'sales_channel', 'ship_service_level', 'category', 'size', 'courier_status', 'currency', 'ship_city', 'ship_state', 'ship_country', 'b2b']

['qty', 'amount', 'ship_postal_code']